      - name: Test SSH Connection
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.UBUNTU_VM_IP }}
          username: ${{ secrets.UBUNTU_VM_USER }}
          password: ${{ secrets.UBUNTU_VM_PASSWORD }}
          script: |
            echo "SSH connection is successful"
